### ISSUE TITLE
RFC: add common commands

### ISSUE THREAD

**Issue by lukepighetti** [s0kil/mint-vscode#9]
It seems to me that we should add the following commands to the VSCode command palette at a minimum. Thoughts?

- `mint build`
- `mint init`
- `mint install`

**Comment by lukepighetti** [comment]
I have this working on https://github.com/lukepighetti/mint-vscode/tree/feat/basic-commands but I'm not convinced it's a value add. Thoughts?

**Comment by s0kil** [comment]
How will `mint init` behave? Will VS Code provide an option where to save the generated project?

**Comment by lukepighetti** [comment]
Yes I would mode it after the Flutter tooling. It would ask what name and where, then create and open the project.

**Comment by s0kil** [comment]
Let's do it.

**Comment by lukepighetti** [comment]
Resolved by https://github.com/s0kil/mint-vscode/pull/10
